baseURL: "https://blog.bugme.tech/"
title: Blog
copyright: "© [Ivan Deyna](https://github.com/literally-bug-creator)"
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts"]

minify:
  disableXML: true
  # minifyOutput: true

pagination:
  disableAliases: false
  pagerSize: 5

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "Blog"
  author: Ivan Deyna

  defaultTheme: dark
  disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  comments: false
  images: ["images/papermod-cover.png"]

  profileMode:
    enabled: true
    title: "Ivan Deyna"
    subtitle: "Software Developer & Tech Enthusiast"
    imageUrl: "images/avatar.jpg"
    imageWidth: 250
    imageHeight: 250
    imageTitle: "Ivan Deyna"
    buttons:
      - name: Posts
        url: posts
      - name: Archive
        url: archives

  # homeInfoParams:
  #   Title: "Ivan Deyna's blog"
  #   Content: >
  #     👋 Welcome to my blog!

  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/literally-bug-creator"
    - name: telegram
      title: My Telegram
      url: "https://t.me/literally_bug_creator"

  editPost:
    URL: "https://github.com/literally-bug-creator/blog/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  assets:
    disableHLJS: true
    favicon: "images/favicon.ico"
    favicon16x16: "images/favicon-96x96.png"
    favicon32x32: "images/favicon-96x96.png"
    apple_touch_icon: "images/apple-touch-icon.png"
    safari_pinned_tab: "images/favicon.svg"
    theme_color: "#1e1e2e"
    msapplication_TileColor: "#1e1e2e"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  googleAnalytics:
    ID: "G-2BVVEQESD6"
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true
