services:
  hugo:
    image: hugomods/hugo:latest
    container_name: hugo
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "1313"
    volumes:
      - ./src:/src
      - ./public:/target
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: "/entrypoint.sh"
    working_dir: /src

networks:
  default:
    external: true
    name: ${EXTERNAL_NETWORK:-nginxpm}
