x-logging: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "100m"
      max-file: "3"

services:
  blog:
    image: hugomods/hugo:exts-non-root
    container_name: hugo_blog
    restart: always
    # user: "1001:1001"
    ports:
      - "1313:1313"
    environment:
      - HUGO_CACHEDIR=/tmp/hugo_cache
    volumes:
      - "./src:/src"
    command: "hugo server --bind 0.0.0.0 --appendPort=false --disableFastRender"
    <<: *logging

networks:
  default:
    name: ${EXTERNAL_NETWORK}
    external: true
